version: '3.9'

services:
  db:
    image: davidrrf/pokebase:latest
    container_name: db

  dl:
    image: davidrrf/pokeloader:latest
    container_name: dl
    depends_on:
      - db

  api:
    image: davidrrf/pokemon_api:latest
    container_name: api
    depends_on:
      - db
      - dl

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - api
      - db
      - dl
