version: '3.9'

services:
  api:
    image: ${{ secrets.DOCKER_HUB_USERNAME }}/pokemon_api:latest
    container_name: api

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - api