from tortoise import fields, models

class Pokemon(models.Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(255)
    japanese_name = fields.CharField(255, null=True)
    pokedex_number = fields.IntField(null=True)
    percentage_male = fields.FloatField(null=True)
    height_m = fields.FloatField(null=True)
    weight_kg = fields.FloatField(null=True)
    hp = fields.IntField(null=True)
    attack = fields.IntField(null=True)
    defense = fields.IntField(null=True)
    speed = fields.IntField(null=True)
    sp_attack = fields.IntField(null=True)
    sp_defense = fields.IntField(null=True)
    type1 = fields.CharField(50, null=True)
    type2 = fields.CharField(50, null=True)
    generation = fields.IntField(null=True)
    is_legendary = fields.BooleanField(null=True)
    classfication = fields.CharField(255, null=True)
    experience_growth = fields.IntField(null=True)
    base_happiness = fields.IntField(null=True)
    base_total = fields.IntField(null=True)
    capture_rate = fields.CharField(10, null=True)
    base_egg_steps = fields.IntField(null=True)
    against_bug = fields.FloatField(null=True)
    against_dark = fields.FloatField(null=True)
    against_dragon = fields.FloatField(null=True)
    against_electric = fields.FloatField(null=True)
    against_fairy = fields.FloatField(null=True)
    against_fight = fields.FloatField(null=True)
    against_fire = fields.FloatField(null=True)
    against_flying = fields.FloatField(null=True)
    against_ghost = fields.FloatField(null=True)
    against_grass = fields.FloatField(null=True)
    against_ground = fields.FloatField(null=True)
    against_ice = fields.FloatField(null=True)
    against_normal = fields.FloatField(null=True)
    against_poison = fields.FloatField(null=True)
    against_psychic = fields.FloatField(null=True)
    against_rock = fields.FloatField(null=True)
    against_steel = fields.FloatField(null=True)
    against_water = fields.FloatField(null=True)
    pokemon_image = fields.CharField(1000, null=True)

    abilities = fields.ReverseRelation["Ability"]

class Ability(models.Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(255)
    pokemon = fields.ForeignKeyField("models.Pokemon", related_name="abilities", on_delete=fields.CASCADE)