CREATE TABLE pokemon (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    japanese_name VARCHAR(255),
    pokedex_number INTEGER,
    percentage_male FLOAT,
    height_m FLOAT,
    weight_kg FLOAT,
    hp INTEGER,
    attack INTEGER,
    defense INTEGER,
    speed INTEGER,
    sp_attack INTEGER,
    sp_defense INTEGER,
    type1 VARCHAR(50),
    type2 VARCHAR(50),
    generation INTEGER,
    is_legendary BOOLEAN,
    classfication VARCHAR(255),
    experience_growth INTEGER,
    base_happiness INTEGER,
    base_total INTEGER,
    capture_rate VARCHAR(255),
    base_egg_steps INTEGER,
    against_bug FLOAT,
    against_dark FLOAT,
    against_dragon FLOAT,
    against_electric FLOAT,
    against_fairy FLOAT,
    against_fight FLOAT,
    against_fire FLOAT,
    against_flying FLOAT,
    against_ghost FLOAT,
    against_grass FLOAT,
    against_ground FLOAT,
    against_ice FLOAT,
    against_normal FLOAT,
    against_poison FLOAT,
    against_psychic FLOAT,
    against_rock FLOAT,
    against_steel FLOAT,
    against_water FLOAT,
    pokemon_image VARCHAR(255)
);

CREATE TABLE ability (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    pokemon_id INTEGER,
    FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE
);