CREATE TABLE pokemon (
    id SERIAL PRIMARY KEY,
    abilities VARCHAR(255)[],
    name VARCHAR(255) NOT NULL,
    japanese_name VARCHAR(255),
    pokedex_number INTEGER,
    percentage_male FLOAT,
    height_m FLOAT,
    weight_kg FLOAT,
    hp INTEGER,
    attack INTEGER,
    defense INTEGER,
    speed INTEGER,
    sp_attack INTEGER,
    sp_defense INTEGER,
    type1 VARCHAR(50),
    type2 VARCHAR(50),
    generation INTEGER,
    is_legendary BOOLEAN,
    classfication VARCHAR(255),
    experience_growth INTEGER,
    base_happiness INTEGER,
    base_total INTEGER,
    capture_rate VARCHAR(255),
    base_egg_steps INTEGER,
    against_bug FLOAT,
    against_dark FLOAT,
    against_dragon FLOAT,
    against_electric FLOAT,
    against_fairy FLOAT,
    against_fight FLOAT,
    against_fire FLOAT,
    against_flying FLOAT,
    against_ghost FLOAT,
    against_grass FLOAT,
    against_ground FLOAT,
    against_ice FLOAT,
    against_normal FLOAT,
    against_poison FLOAT,
    against_psychic FLOAT,
    against_rock FLOAT,
    against_steel FLOAT,
    against_water FLOAT,
    pokemon_image VARCHAR(255),
    image_vector vector(2048)
);

COPY pokemon (
    abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,against_grass,against_ground,against_ice,against_normal,against_poison,against_psychic,against_rock,against_steel,against_water,attack,base_egg_steps,base_happiness,base_total,capture_rate,classfication,defense,experience_growth,height_m,hp,japanese_name,name,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,pokemon_image,image_vector) 
    FROM '/csv/pokemon-info.csv' 
    WITH(FORMAT CSV, DELIMITER ',', HEADER, NULL '', QUOTE "'", ESCAPE '\', ENCODING 'WIN1252');